### ISSUE TITLE
Noise in the results

### ISSUE THREAD

**Issue by rakesh-reddy95** [Cheeun/AdaBM#2]
Hi @Cheeun I have just did an inference with edsr_baseline_x4.pt but the results are just noise. 
Below is the command used:
!python main.py \
    --model EDSR --scale 4 \
    --n_feats 64 --n_resblocks 16 --res_scale 1.0 \
    --data_test Set5 \
    --quantize_a 4 --quantize_w 4 \
    --imgwise --layerwise \
    --test_only \
    --save edsrbaseline_x4/w4a4-adabm-fq-test \
    --pre_train edsr_baseline_x4.pt \
    --fq \
    --test_patch --test_patch_size 96 --test_step_size 96 \
    --test_own 'lenna.png' \
    --save_results

![lenna_x4_3 00bit](https://github.com/Cheeun/AdaBM/assets/20672248/6bc9cc96-0270-4118-a17c-32a41445b608)
May I know what could be the reason?

**Comment by Cheeun** [comment]
Hi, thanks for your interest in our work!
edsr_baseline_x4.pt is the weights of original FP32 EDSR model used for training.
For testing, you have to set the _pre_train_ as the directory for the EDSR-AdaBM model, which can be obtained by running edsr_fq in run.sh. (the model can be obtained within 2 min!) 
For the convenience, I will add the pretrained edsr-adabm model and will let you know.
Hope this answers your question!

**Comment by Cheeun** [comment]
Hi @rakesh-reddy95,
I have added some checkpoints for testing in [link](https://drive.google.com/drive/folders/1GLuvwy3WWFG2H6iEA6-7tqRj_Jnzcn86?usp=drive_link).
You can now run evaluation using these checkpoints!

**Comment by rakesh-reddy95** [comment]
Thank you @Cheeun
