### ISSUE TITLE
How to test On-device latency？

### ISSUE THREAD

**Issue by vokkko** [Cheeun/AdaBM#4]
It's a nice work for SR quantization. I have a question that how can i test the model latency on different device? Could you please provide some details for inference time ?

**Comment by Cheeun** [comment]
Dear @vokkko, I am sorry for such a delayed response.
To measure the latency on CPU, I used torch.quantization library.
Please refer to [this tutorial](https://pytorch.org/docs/stable/quantization.html) for details, I followed it directly for my implementation.
I will include the latency measurement feature in this repo in the future. 
Please stay tuned! Thanks for your attention!
