### ISSUE TITLE
EDSR-2X pretrained model

### ISSUE THREAD

**Issue by qiulinzhang** [Cheeun/AdaBM#6]
Thanks for your great work. Could you please provide a EDSR-2X pretrained model on google drive?

**Comment by Cheeun** [comment]
Sure, the edsr (x2) models are now uploaded in [Google Drive](https://drive.google.com/drive/folders/1GLuvwy3WWFG2H6iEA6-7tqRj_Jnzcn86?usp=drive_link)!
Thanks for your interest in our work!
